on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  issues: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          config-file: config/release-please.json

  build-and-upload:
    if: needs.release-please.outputs.release_created == 'true'
    needs: release-please
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ needs.release-please.outputs.tag_name }}
      
      - uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      
      - name: Build userland format with bundled StringProcs
        run: bun run build
      
      - name: Create StringProc tarball
        run: |
          cd userland
          tar -czf ../stringprocs.tar.gz stringprocs/
          cd ..
        
      - name: Validate userland mapdb.json
        run: bun run validate
      
      - name: Upload release assets
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release upload ${{ needs.release-please.outputs.tag_name }} mapdb.json --clobber
          gh release upload ${{ needs.release-please.outputs.tag_name }} stringprocs.tar.gz --clobber